version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: python src/main.py
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/data

volumes:
  db_data: