version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    environment:
      - DATABASE_URL=sqlite:///app/database/events.db
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/data

volumes:
  db_data: