version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: python src/main.py
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///app/database/events.db
      - BLUESKY_DISCOVEROSHKOSH_PASSWORD=${BLUESKY_DISCOVEROSHKOSH_PASSWORD}
      - BLUESKY_WISCONSINEVENTS_PASSWORD=${BLUESKY_WISCONSINEVENTS_PASSWORD}

  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/data

volumes:
  db_data: